version: '3.9'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: vectorscaledb
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.d/prepare_similarity_search_service_db.sql:/docker-entrypoint-initdb.d/prepare_similarity_search_service_db.sql:ro
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
    driver: local